src/Entity/Picture.php
<?php

namespace App\Entity;

use App\Repository\PictureRepository;
use Doctrine\ORM\Mapping as ORM;
// Upload images
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @Vich\Uploadable
 * @ORM\Entity(repositoryClass=PictureRepository::class)
 */
class Picture
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @Vich\UploadableField(mapping="photos", fileNameProperty="image")
     */
    private $imageFile;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $tags;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\ManyToOne(targetEntity=Categorie::class, inversedBy="pictures")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="pictures")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageFile(?File $imageFile = null): self
    {
        $this->imageFile = $imageFile;
        if($imageFile !== null) {
            $this->updated_at = new \DateTimeImmutable();
        }
        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getTags(): ?string
    {
        return $this->tags;
    }

    public function setTags(string $tags): self
    {
        $this->tags = $tags;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getCategory(): ?Categorie
    {
        return $this->category;
    }

    public function setCategory(?Categorie $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\Categorie;
use App\Entity\Picture;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request; // Nous avons besoin d'accéder à la requête pour obtenir le numéro de page
use Knp\Component\Pager\PaginatorInterface; // Nous appelons le bundle KNP Paginator

class HomeController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index(Request $request, PaginatorInterface $paginator): Response
    {
        // Méthode findBy qui permet de récupérer les données avec des critères de filtre et de tri
        $resultPictures = $this->getDoctrine()->getRepository(Picture::class)->findBy([], ['created_at' => 'desc']);

        // Méthode findAll qui permet de récupérer toutes les données
        $categories = $this->getDoctrine()->getRepository(Categorie::class)->findAll();

        // Page par page
        $page = $request->query->getInt('page', 1);
        $pictures = $paginator->paginate(
            $resultPictures, // Requête contenant les données à paginer
            $page === 0 ? 1 : $page, // Numéro de la page en cours, passé dans l'URL, 1 si aucune page
            6 // Nombre de résultats par page
        );

        return $this->render('home/index.html.twig', [
            'pictures' => $pictures,
            'categories' => $categories,
            'resultPictures' => $resultPictures
        ]);
    }

    /**
     * @Route("/category/{id}", name="pictures_by_category")
     */
    public function picturesByCategory($id, Request $request, PaginatorInterface $paginator)
    {
        // dd($id); équivalent de var_dump()

        // On récupère la catégorie suivant l'id (seul l'id fonctionne avec le find())
        $categorie = $this->getDoctrine()->getRepository(Categorie::class)->find($id);
        // Si la catégorie n'existe pas, erreur 404
        if (!$categorie) {
            throw $this->createNotFoundException('La catégorie n\'éxiste pas !');
        }

        // Page par page
        $page = $request->query->getInt('page', 1);
        $pictures = $paginator->paginate(
            $categorie->getPictures(),
            $page === 0 ? 1 : $page,
            6
        );

        return $this->render('home/picturesByCategory.html.twig', [
            'categorie' => $categorie,
            'pictures' => $pictures
        ]);
    }

    /**
     * @Route("/category/picture/{id}", name="picture")
     */
    public function picture($id, Request $request, PaginatorInterface $paginator)
    {
        // On récupère l'image suivant l'id
        $picture = $this->getDoctrine()->getRepository(Picture::class)->find($id);
        if (!$picture) {
            throw $this->createNotFoundException('Cette image n\'éxiste pas !');
        }

        // Page par page
        $page = $request->query->getInt('page', 1);
        $photos = $paginator->paginate(
            $picture->getCategory()->getPictures(),
            $page === 0 ? 1 : $page,
            3
        );

        return $this->render('home/picture.html.twig', [
            'picture' => $picture,
            'photos' => $photos
        ]);
    }


}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil
{% endblock %}

{% block body %}

	{# Catégories #}
	<div class="d-flex justify-content-between">
		{% for categorie in categories %}
			{# path() contient le nom de la route vers laquelle on se redirige #}
			<a href="{{ path('pictures_by_category', { id: categorie.id }) }}" class="text-decoration-none bg-secondary text-light rounded p-1">{{ categorie.name }}</a>
		{% endfor %}
	</div>


	{# Images #}
	<div class="text-center py-5">
		{% for picture in pictures %}
			{# La concaténation en twig se fait avec un tilde ~ (alt+n)  #}
			<a href="{{ path('account_edit_picture', { id: picture.id }) }}">
				<img src="{{ asset('upload/images/photos/'~ picture.image)|imagine_filter('thumbnail') }}" alt="{{ picture.image }}" class="w-25 m-2 h-100"></a>
		{% endfor %}
	</div>

	{{ knp_pagination_render(pictures) }}

{% endblock %}

templates/home/picture.html.twig
{% extends 'base.html.twig' %}

{% block title %}La photo "{{ picture.image }}"
{% endblock %}

{% block body %}

	<h1 class="text-center text-secondary">{{ picture.image }}</h1>


	{# Image #}
	<div
		class="row justify-content-center py-5">
		{# La concaténation en twig se fait avec un tilde ~ (alt+n)  #}
		<div class="col-10 bg-dark p-2 card">
			<a href="{{ asset('upload/images/photos/'~ picture.image) }}">
				<img src="{{ asset('upload/images/photos/'~ picture.image)|imagine_filter('medium') }}" alt="{{ picture.image }}" class="card-img-top"></a>
			<p class="card-text my-2">{{ picture.description }}</p>
			<p class="card-text">Tags :
				{{ picture.tags }}</p>
			<p class="text-muted">{{ picture.createdAt|date }}</p>
		</div>
	</div>
	<hr class="bg-light">

	<h1 class="text-center text-secondary">Catégorie : {{ picture.category.name }}</h1>
	{# Images de la même catégorie (picture->category->pictures) #}
    {# is same as() correspond à ===, is not same as() à !== #}
	<div class="text-center py-5">
		{% for photo in photos %}
			{% if photo.id is not same as(picture.id) %}
				<a href="{{ path('picture', { id: photo.id }) }}">
					<img src="{{ asset('upload/images/photos/'~ photo.image)|imagine_filter('thumbnail') }}" alt="{{ photo.image }}" class="w-25 m-2 h-100"></a>
			{% endif %}
		{% endfor %}
	</div>

	{{ knp_pagination_render(photos) }}

{% endblock %}

templates/home/picturesByCategory.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les photos de la catégorie "{{ categorie.name }}"{% endblock %}

{% block body %}

    <h1 class="text-center text-secondary">Catégorie : {{ categorie.name }}</h1>


    {# Images #}
    <div class="row justify-content-around py-5">
        {% for picture in pictures %}
    {# La concaténation en twig se fait avec un tilde ~ (alt+n)  #}
            <a href="{{ path('picture', { id: picture.id }) }}">
            <img src="{{ asset('upload/images/photos/'~ picture.image)|imagine_filter('thumbnail') }}" alt="{{ picture.image }}" class="m-2"></a>
        {% endfor %}
    </div>

    {{ knp_pagination_render(pictures) }}

{% endblock %}